// Eventboat out-of-process plugin protocol v1 (redesign-v3.md §6.5).
//
// A plugin is a subprocess the Eventboat host launches per the node's
// `grpc.command`. Startup handshake: the plugin listens on 127.0.0.1, prints
// one JSON line to stdout, and serves gRPC. Full contract: docs/plugins.md.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.31.1
// source: proto/eventboat/plugin/v1/plugin.proto

package pluginv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// MetaValue is one metadata entry. Scalars only; rich values travel as
// JSON-encoded strings. Keeping this a plain oneof (instead of
// google.protobuf.Value) makes the protocol trivial to implement in any
// language.
type MetaValue struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Kind:
	//
	//	*MetaValue_StringValue
	//	*MetaValue_IntValue
	//	*MetaValue_BoolValue
	//	*MetaValue_DoubleValue
	Kind          isMetaValue_Kind `protobuf_oneof:"kind"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetaValue) Reset() {
	*x = MetaValue{}
	mi := &file_proto_eventboat_plugin_v1_plugin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetaValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetaValue) ProtoMessage() {}

func (x *MetaValue) ProtoReflect() protoreflect.Message {
	mi := &file_proto_eventboat_plugin_v1_plugin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetaValue.ProtoReflect.Descriptor instead.
func (*MetaValue) Descriptor() ([]byte, []int) {
	return file_proto_eventboat_plugin_v1_plugin_proto_rawDescGZIP(), []int{0}
}

func (x *MetaValue) GetKind() isMetaValue_Kind {
	if x != nil {
		return x.Kind
	}
	return nil
}

func (x *MetaValue) GetStringValue() string {
	if x != nil {
		if x, ok := x.Kind.(*MetaValue_StringValue); ok {
			return x.StringValue
		}
	}
	return ""
}

func (x *MetaValue) GetIntValue() int64 {
	if x != nil {
		if x, ok := x.Kind.(*MetaValue_IntValue); ok {
			return x.IntValue
		}
	}
	return 0
}

func (x *MetaValue) GetBoolValue() bool {
	if x != nil {
		if x, ok := x.Kind.(*MetaValue_BoolValue); ok {
			return x.BoolValue
		}
	}
	return false
}

func (x *MetaValue) GetDoubleValue() float64 {
	if x != nil {
		if x, ok := x.Kind.(*MetaValue_DoubleValue); ok {
			return x.DoubleValue
		}
	}
	return 0
}

type isMetaValue_Kind interface {
	isMetaValue_Kind()
}

type MetaValue_StringValue struct {
	StringValue string `protobuf:"bytes,1,opt,name=string_value,json=stringValue,proto3,oneof"`
}

type MetaValue_IntValue struct {
	IntValue int64 `protobuf:"varint,2,opt,name=int_value,json=intValue,proto3,oneof"`
}

type MetaValue_BoolValue struct {
	BoolValue bool `protobuf:"varint,3,opt,name=bool_value,json=boolValue,proto3,oneof"`
}

type MetaValue_DoubleValue struct {
	DoubleValue float64 `protobuf:"fixed64,4,opt,name=double_value,json=doubleValue,proto3,oneof"`
}

func (*MetaValue_StringValue) isMetaValue_Kind() {}

func (*MetaValue_IntValue) isMetaValue_Kind() {}

func (*MetaValue_BoolValue) isMetaValue_Kind() {}

func (*MetaValue_DoubleValue) isMetaValue_Kind() {}

// Event is one message crossing the process boundary. Payload is raw bytes
// exactly as the engine holds it (decoded form is the plugin's business).
type Event struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Payload       []byte                 `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	Meta          map[string]*MetaValue  `protobuf:"bytes,2,rep,name=meta,proto3" json:"meta,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Codec         string                 `protobuf:"bytes,3,opt,name=codec,proto3" json:"codec,omitempty"`                  // codec name the payload arrived with
	Cursor        string                 `protobuf:"bytes,4,opt,name=cursor,proto3" json:"cursor,omitempty"`                // pull sources: cursor column value ("" if none)
	SrcSeq        int64                  `protobuf:"varint,5,opt,name=src_seq,json=srcSeq,proto3" json:"src_seq,omitempty"` // per-source monotonic sequence
	SrcName       string                 `protobuf:"bytes,6,opt,name=src_name,json=srcName,proto3" json:"src_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_proto_eventboat_plugin_v1_plugin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_proto_eventboat_plugin_v1_plugin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_proto_eventboat_plugin_v1_plugin_proto_rawDescGZIP(), []int{1}
}

func (x *Event) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Event) GetMeta() map[string]*MetaValue {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *Event) GetCodec() string {
	if x != nil {
		return x.Codec
	}
	return ""
}

func (x *Event) GetCursor() string {
	if x != nil {
		return x.Cursor
	}
	return ""
}

func (x *Event) GetSrcSeq() int64 {
	if x != nil {
		return x.SrcSeq
	}
	return 0
}

func (x *Event) GetSrcName() string {
	if x != nil {
		return x.SrcName
	}
	return ""
}

type InitRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	State         []byte                 `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`                             // persisted source state (empty on first run)
	ConfigJson    string                 `protobuf:"bytes,2,opt,name=config_json,json=configJson,proto3" json:"config_json,omitempty"` // the node's plugin block as JSON
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitRequest) Reset() {
	*x = InitRequest{}
	mi := &file_proto_eventboat_plugin_v1_plugin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitRequest) ProtoMessage() {}

func (x *InitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_eventboat_plugin_v1_plugin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitRequest.ProtoReflect.Descriptor instead.
func (*InitRequest) Descriptor() ([]byte, []int) {
	return file_proto_eventboat_plugin_v1_plugin_proto_rawDescGZIP(), []int{2}
}

func (x *InitRequest) GetState() []byte {
	if x != nil {
		return x.State
	}
	return nil
}

func (x *InitRequest) GetConfigJson() string {
	if x != nil {
		return x.ConfigJson
	}
	return ""
}

type InitResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"` // "" = ok
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitResponse) Reset() {
	*x = InitResponse{}
	mi := &file_proto_eventboat_plugin_v1_plugin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitResponse) ProtoMessage() {}

func (x *InitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_eventboat_plugin_v1_plugin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitResponse.ProtoReflect.Descriptor instead.
func (*InitResponse) Descriptor() ([]byte, []int) {
	return file_proto_eventboat_plugin_v1_plugin_proto_rawDescGZIP(), []int{3}
}

func (x *InitResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type RunRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunRequest) Reset() {
	*x = RunRequest{}
	mi := &file_proto_eventboat_plugin_v1_plugin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunRequest) ProtoMessage() {}

func (x *RunRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_eventboat_plugin_v1_plugin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunRequest.ProtoReflect.Descriptor instead.
func (*RunRequest) Descriptor() ([]byte, []int) {
	return file_proto_eventboat_plugin_v1_plugin_proto_rawDescGZIP(), []int{4}
}

type CommitRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ThroughSrcSeq int64                  `protobuf:"varint,1,opt,name=through_src_seq,json=throughSrcSeq,proto3" json:"through_src_seq,omitempty"` // commit frontier advanced through this seq
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommitRequest) Reset() {
	*x = CommitRequest{}
	mi := &file_proto_eventboat_plugin_v1_plugin_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitRequest) ProtoMessage() {}

func (x *CommitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_eventboat_plugin_v1_plugin_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitRequest.ProtoReflect.Descriptor instead.
func (*CommitRequest) Descriptor() ([]byte, []int) {
	return file_proto_eventboat_plugin_v1_plugin_proto_rawDescGZIP(), []int{5}
}

func (x *CommitRequest) GetThroughSrcSeq() int64 {
	if x != nil {
		return x.ThroughSrcSeq
	}
	return 0
}

type CommitResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	State         []byte                 `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"` // new state to persist (nil = unchanged)
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommitResponse) Reset() {
	*x = CommitResponse{}
	mi := &file_proto_eventboat_plugin_v1_plugin_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitResponse) ProtoMessage() {}

func (x *CommitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_eventboat_plugin_v1_plugin_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitResponse.ProtoReflect.Descriptor instead.
func (*CommitResponse) Descriptor() ([]byte, []int) {
	return file_proto_eventboat_plugin_v1_plugin_proto_rawDescGZIP(), []int{6}
}

func (x *CommitResponse) GetState() []byte {
	if x != nil {
		return x.State
	}
	return nil
}

func (x *CommitResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type CloseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloseRequest) Reset() {
	*x = CloseRequest{}
	mi := &file_proto_eventboat_plugin_v1_plugin_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseRequest) ProtoMessage() {}

func (x *CloseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_eventboat_plugin_v1_plugin_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseRequest.ProtoReflect.Descriptor instead.
func (*CloseRequest) Descriptor() ([]byte, []int) {
	return file_proto_eventboat_plugin_v1_plugin_proto_rawDescGZIP(), []int{7}
}

type CloseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloseResponse) Reset() {
	*x = CloseResponse{}
	mi := &file_proto_eventboat_plugin_v1_plugin_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseResponse) ProtoMessage() {}

func (x *CloseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_eventboat_plugin_v1_plugin_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseResponse.ProtoReflect.Descriptor instead.
func (*CloseResponse) Descriptor() ([]byte, []int) {
	return file_proto_eventboat_plugin_v1_plugin_proto_rawDescGZIP(), []int{8}
}

func (x *CloseResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type WriteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Batch         []*Event               `protobuf:"bytes,1,rep,name=batch,proto3" json:"batch,omitempty"` // batching is engine-owned; plugins just write
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteRequest) Reset() {
	*x = WriteRequest{}
	mi := &file_proto_eventboat_plugin_v1_plugin_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteRequest) ProtoMessage() {}

func (x *WriteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_eventboat_plugin_v1_plugin_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteRequest.ProtoReflect.Descriptor instead.
func (*WriteRequest) Descriptor() ([]byte, []int) {
	return file_proto_eventboat_plugin_v1_plugin_proto_rawDescGZIP(), []int{9}
}

func (x *WriteRequest) GetBatch() []*Event {
	if x != nil {
		return x.Batch
	}
	return nil
}

type WriteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteResponse) Reset() {
	*x = WriteResponse{}
	mi := &file_proto_eventboat_plugin_v1_plugin_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteResponse) ProtoMessage() {}

func (x *WriteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_eventboat_plugin_v1_plugin_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteResponse.ProtoReflect.Descriptor instead.
func (*WriteResponse) Descriptor() ([]byte, []int) {
	return file_proto_eventboat_plugin_v1_plugin_proto_rawDescGZIP(), []int{10}
}

func (x *WriteResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_proto_eventboat_plugin_v1_plugin_proto protoreflect.FileDescriptor

const file_proto_eventboat_plugin_v1_plugin_proto_rawDesc = "" +
	"\n" +
	"&proto/eventboat/plugin/v1/plugin.proto\x12\x13eventboat.plugin.v1\"\x9d\x01\n" +
	"\tMetaValue\x12#\n" +
	"\fstring_value\x18\x01 \x01(\tH\x00R\vstringValue\x12\x1d\n" +
	"\tint_value\x18\x02 \x01(\x03H\x00R\bintValue\x12\x1f\n" +
	"\n" +
	"bool_value\x18\x03 \x01(\bH\x00R\tboolValue\x12#\n" +
	"\fdouble_value\x18\x04 \x01(\x01H\x00R\vdoubleValueB\x06\n" +
	"\x04kind\"\x96\x02\n" +
	"\x05Event\x12\x18\n" +
	"\apayload\x18\x01 \x01(\fR\apayload\x128\n" +
	"\x04meta\x18\x02 \x03(\v2$.eventboat.plugin.v1.Event.MetaEntryR\x04meta\x12\x14\n" +
	"\x05codec\x18\x03 \x01(\tR\x05codec\x12\x16\n" +
	"\x06cursor\x18\x04 \x01(\tR\x06cursor\x12\x17\n" +
	"\asrc_seq\x18\x05 \x01(\x03R\x06srcSeq\x12\x19\n" +
	"\bsrc_name\x18\x06 \x01(\tR\asrcName\x1aW\n" +
	"\tMetaEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x124\n" +
	"\x05value\x18\x02 \x01(\v2\x1e.eventboat.plugin.v1.MetaValueR\x05value:\x028\x01\"D\n" +
	"\vInitRequest\x12\x14\n" +
	"\x05state\x18\x01 \x01(\fR\x05state\x12\x1f\n" +
	"\vconfig_json\x18\x02 \x01(\tR\n" +
	"configJson\"$\n" +
	"\fInitResponse\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error\"\f\n" +
	"\n" +
	"RunRequest\"7\n" +
	"\rCommitRequest\x12&\n" +
	"\x0fthrough_src_seq\x18\x01 \x01(\x03R\rthroughSrcSeq\"<\n" +
	"\x0eCommitResponse\x12\x14\n" +
	"\x05state\x18\x01 \x01(\fR\x05state\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"\x0e\n" +
	"\fCloseRequest\"%\n" +
	"\rCloseResponse\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error\"@\n" +
	"\fWriteRequest\x120\n" +
	"\x05batch\x18\x01 \x03(\v2\x1a.eventboat.plugin.v1.EventR\x05batch\"%\n" +
	"\rWriteResponse\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error2\x85\x03\n" +
	"\x06Source\x12K\n" +
	"\x04Init\x12 .eventboat.plugin.v1.InitRequest\x1a!.eventboat.plugin.v1.InitResponse\x12D\n" +
	"\x03Run\x12\x1f.eventboat.plugin.v1.RunRequest\x1a\x1a.eventboat.plugin.v1.Event0\x01\x12E\n" +
	"\x04Pull\x12\x1f.eventboat.plugin.v1.RunRequest\x1a\x1a.eventboat.plugin.v1.Event0\x01\x12Q\n" +
	"\x06Commit\x12\".eventboat.plugin.v1.CommitRequest\x1a#.eventboat.plugin.v1.CommitResponse\x12N\n" +
	"\x05Close\x12!.eventboat.plugin.v1.CloseRequest\x1a\".eventboat.plugin.v1.CloseResponse2\xf3\x01\n" +
	"\x04Sink\x12K\n" +
	"\x04Init\x12 .eventboat.plugin.v1.InitRequest\x1a!.eventboat.plugin.v1.InitResponse\x12N\n" +
	"\x05Write\x12!.eventboat.plugin.v1.WriteRequest\x1a\".eventboat.plugin.v1.WriteResponse\x12N\n" +
	"\x05Close\x12!.eventboat.plugin.v1.CloseRequest\x1a\".eventboat.plugin.v1.CloseResponseB-Z+github.com/eventboat/eventboat/pkg/pluginv1b\x06proto3"

var (
	file_proto_eventboat_plugin_v1_plugin_proto_rawDescOnce sync.Once
	file_proto_eventboat_plugin_v1_plugin_proto_rawDescData []byte
)

func file_proto_eventboat_plugin_v1_plugin_proto_rawDescGZIP() []byte {
	file_proto_eventboat_plugin_v1_plugin_proto_rawDescOnce.Do(func() {
		file_proto_eventboat_plugin_v1_plugin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_eventboat_plugin_v1_plugin_proto_rawDesc), len(file_proto_eventboat_plugin_v1_plugin_proto_rawDesc)))
	})
	return file_proto_eventboat_plugin_v1_plugin_proto_rawDescData
}

var file_proto_eventboat_plugin_v1_plugin_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_proto_eventboat_plugin_v1_plugin_proto_goTypes = []any{
	(*MetaValue)(nil),      // 0: eventboat.plugin.v1.MetaValue
	(*Event)(nil),          // 1: eventboat.plugin.v1.Event
	(*InitRequest)(nil),    // 2: eventboat.plugin.v1.InitRequest
	(*InitResponse)(nil),   // 3: eventboat.plugin.v1.InitResponse
	(*RunRequest)(nil),     // 4: eventboat.plugin.v1.RunRequest
	(*CommitRequest)(nil),  // 5: eventboat.plugin.v1.CommitRequest
	(*CommitResponse)(nil), // 6: eventboat.plugin.v1.CommitResponse
	(*CloseRequest)(nil),   // 7: eventboat.plugin.v1.CloseRequest
	(*CloseResponse)(nil),  // 8: eventboat.plugin.v1.CloseResponse
	(*WriteRequest)(nil),   // 9: eventboat.plugin.v1.WriteRequest
	(*WriteResponse)(nil),  // 10: eventboat.plugin.v1.WriteResponse
	nil,                    // 11: eventboat.plugin.v1.Event.MetaEntry
}
var file_proto_eventboat_plugin_v1_plugin_proto_depIdxs = []int32{
	11, // 0: eventboat.plugin.v1.Event.meta:type_name -> eventboat.plugin.v1.Event.MetaEntry
	1,  // 1: eventboat.plugin.v1.WriteRequest.batch:type_name -> eventboat.plugin.v1.Event
	0,  // 2: eventboat.plugin.v1.Event.MetaEntry.value:type_name -> eventboat.plugin.v1.MetaValue
	2,  // 3: eventboat.plugin.v1.Source.Init:input_type -> eventboat.plugin.v1.InitRequest
	4,  // 4: eventboat.plugin.v1.Source.Run:input_type -> eventboat.plugin.v1.RunRequest
	4,  // 5: eventboat.plugin.v1.Source.Pull:input_type -> eventboat.plugin.v1.RunRequest
	5,  // 6: eventboat.plugin.v1.Source.Commit:input_type -> eventboat.plugin.v1.CommitRequest
	7,  // 7: eventboat.plugin.v1.Source.Close:input_type -> eventboat.plugin.v1.CloseRequest
	2,  // 8: eventboat.plugin.v1.Sink.Init:input_type -> eventboat.plugin.v1.InitRequest
	9,  // 9: eventboat.plugin.v1.Sink.Write:input_type -> eventboat.plugin.v1.WriteRequest
	7,  // 10: eventboat.plugin.v1.Sink.Close:input_type -> eventboat.plugin.v1.CloseRequest
	3,  // 11: eventboat.plugin.v1.Source.Init:output_type -> eventboat.plugin.v1.InitResponse
	1,  // 12: eventboat.plugin.v1.Source.Run:output_type -> eventboat.plugin.v1.Event
	1,  // 13: eventboat.plugin.v1.Source.Pull:output_type -> eventboat.plugin.v1.Event
	6,  // 14: eventboat.plugin.v1.Source.Commit:output_type -> eventboat.plugin.v1.CommitResponse
	8,  // 15: eventboat.plugin.v1.Source.Close:output_type -> eventboat.plugin.v1.CloseResponse
	3,  // 16: eventboat.plugin.v1.Sink.Init:output_type -> eventboat.plugin.v1.InitResponse
	10, // 17: eventboat.plugin.v1.Sink.Write:output_type -> eventboat.plugin.v1.WriteResponse
	8,  // 18: eventboat.plugin.v1.Sink.Close:output_type -> eventboat.plugin.v1.CloseResponse
	11, // [11:19] is the sub-list for method output_type
	3,  // [3:11] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_proto_eventboat_plugin_v1_plugin_proto_init() }
func file_proto_eventboat_plugin_v1_plugin_proto_init() {
	if File_proto_eventboat_plugin_v1_plugin_proto != nil {
		return
	}
	file_proto_eventboat_plugin_v1_plugin_proto_msgTypes[0].OneofWrappers = []any{
		(*MetaValue_StringValue)(nil),
		(*MetaValue_IntValue)(nil),
		(*MetaValue_BoolValue)(nil),
		(*MetaValue_DoubleValue)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_eventboat_plugin_v1_plugin_proto_rawDesc), len(file_proto_eventboat_plugin_v1_plugin_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_proto_eventboat_plugin_v1_plugin_proto_goTypes,
		DependencyIndexes: file_proto_eventboat_plugin_v1_plugin_proto_depIdxs,
		MessageInfos:      file_proto_eventboat_plugin_v1_plugin_proto_msgTypes,
	}.Build()
	File_proto_eventboat_plugin_v1_plugin_proto = out.File
	file_proto_eventboat_plugin_v1_plugin_proto_goTypes = nil
	file_proto_eventboat_plugin_v1_plugin_proto_depIdxs = nil
}
